In [4]:
import numpy as np

In [5]:
# Creation d'un tableau avec définition du type
np.array([1,2,3,4,5],dtype='float32')
# Remplissage d'un tableau 
np.array([range(i,i+3) for i in [2,4,6]])
# Un tableau de longueur 10, rempli d'entiers qui valent 0
np.zeros(10, dtype=int)
# Un tableau de taille 3x5 rempli de nombres à virgule flottante de valeur 1
np.ones((3, 5), dtype=float)
# Un tableau 3x5 rempli de 3,14
np.full((3, 5), 3.14)
# Un tableau rempli d'une séquence linéaire commençant à 0 et qui se termine à 20, avec un pas de 2
np.arange(0, 20, 2)
# Un tableau de 5 valeurs, espacées uniformément entre 0 et 1
np.linspace(0, 1, 5)
# Celle-ci vous la conaissez déjà! Essayez aussi "randint" et "normal"
np.random.randint(5,7,[2,5])
# La matrice identité de taille 3x3 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)  # Tableau de dimension 1
print("nombre de dimensions de x1: ", x1.ndim)
print("forme de x1: ", x1.shape)
print("taille de x1: ", x1.size)
print("type de x1: ", x1.dtype)

nombre de dimensions de x1:  1
forme de x1:  (6,)
taille de x1:  6
type de x1:  int32


In [7]:
# Pour accéder au premier élément
print(x1[0])
# Pour accéder au dernier élément
print(x1[-1])
x2 = np.random.randint(10, size=(3, 4))  # Tableau de dimension 2
print(x2[0,1])

x1 = np.array([range(i,i+10) for i in [1]])
print(x1[:5])  # Les cinq premiers éléments
print(x1[5:])  # Les éléments à partir de l'index 5
print(x1[::2])  # Un élément sur deux

# Inversion du tableau
x1[::-1]

x2[0,:] # La première ligne
x2[:,0] # La première colonne

5
9
5
[[ 1  2  3  4  5  6  7  8  9 10]]
[]
[[ 1  2  3  4  5  6  7  8  9 10]]


array([3, 7, 1])

In [8]:
# Concaténation
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [9]:
#Opérations arithmétiques sur lestableaux
# Il y a tout d'abord des opération mathématiques simples
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # Division avec arrondi

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [10]:
# Opérations mathématiques
x = [-2, -1, 1, 2]
print("La valeur absolue: ", np.abs(x))
print("Exponentielle: ", np.exp(x))
print("Logarithme: ", np.log(np.abs(x)))

La valeur absolue:  [2 1 1 2]
Exponentielle:  [0.13533528 0.36787944 2.71828183 7.3890561 ]
Logarithme:  [0.69314718 0.         0.         0.69314718]


In [11]:
# Opérations booléennes
x = np.random.rand(3,3)
np.where(x > 0.5)

(array([0, 1, 2, 2], dtype=int64), array([2, 1, 0, 2], dtype=int64))

In [12]:
# Agrégation
L = np.random.random(100)
np.sum(L)
np.max(L)
np.min(L)

0.009356704856532616

In [13]:
# Notez la syntax variable.fonction au lieu de # np.fonction(variable)
M = np.random.random((3, 4))
print(M)
print("La somme de tous les éléments de M: ", M.sum())
print("Les sommes des colonnes de M: ", M.sum(axis=0))
# Ecart Type
print(M.std())
# index du minimum
print(M.argmin())
# index du minimum pour chaque colonne
print(M.argmin(axis=0))
# index du minimum pour chaque ligne
print(M.argmin(axis=1))
# Calcul de percentiles
print(np.percentile(M,0.75))

[[0.65966841 0.53320625 0.23053302 0.39486929]
 [0.61880856 0.47486752 0.47013219 0.71607453]
 [0.287991   0.38346223 0.74916984 0.87845219]]
La somme de tous les éléments de M:  6.397235040254322
Les sommes des colonnes de M:  [1.56646798 1.39153599 1.44983505 1.98939601]
0.18781193507680735
2
[2 2 0 0]
[2 2 0]
0.23527330692702828


In [14]:
# Broadcasting
M = np.ones((3, 3))
print("M vaut: \n", M)
print("M+ 5 vaut: \n", M+5)

M vaut: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
M+ 5 vaut: 
 [[6. 6. 6.]
 [6. 6. 6.]
 [6. 6. 6.]]


In [15]:
# La ligne suivante crée une matrice de taille 3x1 avec trois lignes et une colonne.
a = np.arange(3)
b = np.arange(3)[:, np.newaxis]
print(a)
print(b)
print(a+b)

[0 1 2]
[[0]
 [1]
 [2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [16]:
# Utilisation de masques
np.random.seed(3)
a = np.random.randint(0, 21, 15)
print(a)
(a % 3 == 0)
mask = (a % 3 == 0)
extract_from_a = a[mask] # or, a[a%3==0]
print(extract_from_a)  # extract a sub-array with the mask

[10  3  8  0 19 10 11  9 10  6  0 20 12  7 14]
[ 3  0  9  6  0 12]


In [17]:
# Assign new values to index
a[a % 3 == 0] = -1
print(a)

[10 -1  8 -1 19 10 11 -1 10 -1 -1 20 -1  7 14]
