In [1]:
import numpy as np
import pandas as pd

In [4]:
famille_panda = [
    np.array([100, 5  , 20, 80]), # maman panda
    np.array([50 , 2.5, 10, 40]), # bébé panda
    np.array([110, 6  , 22, 80]), # papa panda
]
famille_panda

[array([100,   5,  20,  80]),
 array([50. ,  2.5, 10. , 40. ]),
 array([110,   6,  22,  80])]

In [3]:
famille_panda = [
    [100, 5  , 20, 80], # maman panda
    [50 , 2.5, 10, 40], # bébé panda
    [110, 6  , 22, 80], # papa panda
]
famille_panda_numpy = np.array(famille_panda)
famille_panda_numpy

array([[100. ,   5. ,  20. ,  80. ],
       [ 50. ,   2.5,  10. ,  40. ],
       [110. ,   6. ,  22. ,  80. ]])

In [7]:
famille_panda_numpy[2,0]
famille_panda_numpy[:,0]

array([100.,  50., 110.])

In [8]:
famille_pandas_df = pd.DataFrame(famille_panda)
famille_pandas_df

0    1     2     3
0  100.0  5.0  20.0  80.0
1   50.0  2.5  10.0  40.0
2  110.0  6.0  22.0  80.0

In [10]:
famille_panda_df = pd.DataFrame(famille_panda_numpy,index=['maman','bébé','papa'],columns=['pattes','poil','queue','ventre'])
famille_panda_df

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
bébé     50.0   2.5   10.0    40.0
papa    110.0   6.0   22.0    80.0

In [12]:
famille_panda_df["ventre"]

maman    80.0
bébé     40.0
papa     80.0
Name: ventre, dtype: float64

In [13]:
famille_panda_df.ventre

maman    80.0
bébé     40.0
papa     80.0
Name: ventre, dtype: float64

In [14]:
famille_panda_df["ventre"].values

array([80., 40., 80.])

In [15]:
famille_panda_df.ventre.values

array([80., 40., 80.])

In [16]:
for ligne in famille_panda_df.iterrows():
    index_ligne = ligne[0]
    contenu_ligne = ligne[1]
    print("Voici le panda %s :" % index_ligne)
    print(contenu_ligne)
    print("--------------------")

Voici le panda maman :
pattes    100.0
poil        5.0
queue      20.0
ventre     80.0
Name: maman, dtype: float64
--------------------
Voici le panda bébé :
pattes    50.0
poil       2.5
queue     10.0
ventre    40.0
Name: bébé, dtype: float64
--------------------
Voici le panda papa :
pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64
--------------------


In [17]:
famille_panda_df.iloc[2] # Avec iloc(), indexation positionnelle
famille_panda_df.loc["papa"] # Avec loc(), indexation par label

pattes    110.0
poil        6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64

In [18]:
famille_panda_df["ventre"] == 80

maman     True
bébé     False
papa      True
Name: ventre, dtype: bool

In [20]:
masque = famille_panda_df["ventre"] == 80
pandas_80 = famille_panda_df[masque]
pandas_80 = famille_panda_df[famille_panda_df["ventre"] == 80]
pandas_80

pattes  poil  queue  ventre
maman   100.0   5.0   20.0    80.0
papa    110.0   6.0   22.0    80.0

In [21]:
# Inversion du masque
famille_panda_df[~masque]

pattes  poil  queue  ventre
bébé    50.0   2.5   10.0    40.0

In [23]:
quelques_pandas = pd.DataFrame([[105,4,19,80],[100,5,20,80]],      # deux nouveaux pandas
                               columns = famille_panda_df.columns,
                               index = ['tonton','tata'])                                
tous_les_pandas = famille_panda_df.append(quelques_pandas)
tous_les_pandas

pattes  poil  queue  ventre
maman    100.0   5.0   20.0    80.0
bébé      50.0   2.5   10.0    40.0
papa     110.0   6.0   22.0    80.0
tonton   105.0   4.0   19.0    80.0
tata     100.0   5.0   20.0    80.0

In [25]:
# Déduplication des lignes aux données identiques
pandas_uniques = tous_les_pandas.drop_duplicates()
pandas_uniques

pattes  poil  queue  ventre
maman    100.0   5.0   20.0    80.0
bébé      50.0   2.5   10.0    40.0
papa     110.0   6.0   22.0    80.0
tonton   105.0   4.0   19.0    80.0

In [29]:
# accéder aux noms des colonnes
famille_panda_df.columns
# créer une nouvelle colonne, composée de chaînes de caractères - a maman et le bébé sont des femelles, le papa est un mâle 
famille_panda_df["sexe"] = ["f", "f", "m"] 
famille_panda_df

pattes  poil  queue  ventre sexe
maman   100.0   5.0   20.0    80.0    f
bébé     50.0   2.5   10.0    40.0    f
papa    110.0   6.0   22.0    80.0    m

In [30]:
# obtenir le nombre de lignes
len(famille_panda_df)

3

In [31]:
# obtenir les valeurs distinctes d'une colonne - pour la colonne ventre, il y a deux valeurs distinctes : 40 et 80
famille_panda_df.ventre.unique()

array([80., 40.])

In [33]:
data = pd.read_csv("E:/Data/RawData/IrisData.csv", sep=";")
data.head()

SepalLength  SepalWidth  PetalLength  PetalWidth    Species
0          5.1         3.5          1.4         0.2  I. setosa
1          4.9         3.0          1.4         0.2  I. setosa
2          4.7         3.2          1.3         0.2  I. setosa
3          4.6         3.1          1.5         0.2  I. setosa
4          5.0         3.6          1.4         0.2  I. setosa

In [34]:
# Obtenir le répertoire courant
import os
os.getcwd()

'C:\\Users\\monne\\Documents\\Python Scripts'